

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: DEBUG
spring:
  datasource:
    url:  jdbc:h2:file:./h2/org
  jpa:
    hibernate:
      properties:
        format_sql: true
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
  h2:
    console:
      enabled: true